GET  http://127.0.0.1:8000/api/programacion_riego/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1NzIwMzU2LCJpYXQiOjE3NTU3MjAwNTYsImp0aSI6ImI3MDBkNDk3NTdjMTQ1OWY5ZTMyNjgyNDI5YWI0NjlkIiwidXNlcl9pZCI6IjUifQ.pj01MS7bj5ZU51yUINRT14fglc1VJ4RCvdGobhBA-nM 
content-Type:application/json


//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzU1MDUzMTIzLCJpYXQiOjE3NTUwNTI4MjMsImp0aSI6ImNmNGI5NWM0YjFmNTQzZGE4NjhlMmM2NGYyMWQ3YzZhIiwidXNlcl9pZCI6IjUifQ.YAo6POl2BPfPYfRUc-59evuhmOvqtj10buD8h5-YnzQ
//eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTEzOTg0NCwiaWF0IjoxNzU1MDUzNDQ0LCJqdGkiOiIwZGNiZThhYmNkMDc0ZWFmYTUyMTUzNzM1NmUzNWI2NSIsInVzZXJfaWQiOiI1In0.53s1fBFd9rl_9-jCRhN3QwI4oHSJHrlKNsL5_lSJ6zM